#!/usr/bin/env python3
"""Regenerate ui_background.c from images/background.jpg.

Conversion: images/background.jpg is contain-fit scaled (aspect ratio
preserved, no cropping) to fit within BOX_W x BOX_H -- the home page's
content area between the app bar and bottom button bar, ST7796_W x
(ST7796_H - app bar height - bottom bar height) -- then converted to raw
RGB565 pixels (native uint16_t order -- the compiler lays these out in the
target's native byte order, which is what LVGL's software renderer expects
for LV_COLOR_FORMAT_RGB565 image data). The resulting (possibly smaller)
image dimensions are embedded in the emitted lv_image_dsc_t; ui_shell.c
centers it within the content area at runtime.

Usage (from repo root, needs Pillow: `pip install pillow`):
    python tools/gen_background.py
"""
from PIL import Image

SRC_PATH = "images/background.jpg"
OUT_PATH = "ui_background.c"
BOX_W = 480
BOX_H = 228   # ST7796_H (320) - app bar height (36) - bottom bar height (56), see ui_shell.c


def rgb565_pixels():
    im = Image.open(SRC_PATH).convert("RGB")
    src_w, src_h = im.size
    scale = min(BOX_W / src_w, BOX_H / src_h)
    new_w, new_h = round(src_w * scale), round(src_h * scale)
    im = im.resize((new_w, new_h), Image.LANCZOS)
    pixels = [((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3) for r, g, b in im.getdata()]
    return pixels, new_w, new_h


def main():
    pixels, w, h = rgb565_pixels()
    lines = [
        f"// wilicankit home-page background -- pre-rendered {w}x{h} RGB565",
        "// bitmap. GENERATED by tools/gen_background.py -- do not hand-edit;",
        "// edit images/background.jpg and re-run that script instead.",
        "#include \"ui_background.h\"",
        "#include \"pico/stdlib.h\"   // __in_psram, via pico/platform/sections.h",
        "",
        f'static const uint16_t __in_psram("background") bg_pixels[{len(pixels)}] = {{',
    ]
    for i in range(0, len(pixels), 16):
        row = ", ".join(f"0x{p:04x}" for p in pixels[i:i + 16])
        lines.append(f"    {row},")
    lines.append("};")
    lines += [
        "",
        "const lv_image_dsc_t ui_background = {",
        "    .header = {",
        "        .magic = LV_IMAGE_HEADER_MAGIC,",
        "        .cf = LV_COLOR_FORMAT_RGB565,",
        f"        .w = {w},",
        f"        .h = {h},",
        "    },",
        "    .data_size = sizeof(bg_pixels),",
        "    .data = (const uint8_t *)bg_pixels,",
        "};",
        "",
    ]
    with open(OUT_PATH, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH} ({w}x{h})")


if __name__ == "__main__":
    main()
