#!/usr/bin/env python3
"""Regenerate ui_background.c from images/background.png.

Downscales the source image (Pillow, LANCZOS) to fit within the home
screen's content area (full panel width, minus the app bar and bottom
button bar heights -- see CONTENT_W/CONTENT_H below, kept in sync with
ui_shell.c's app_bar/bottom heights and ST7796_W/H), preserving aspect
ratio, then bakes it as a native little-endian RGB565 (LV_COLOR_FORMAT_RGB565)
lv_image_dsc_t -- same PSRAM-resident (`__in_psram`) approach as
tools/gen_icons.py uses for the nav icons. Source has no meaningful alpha
(fully opaque), so RGB565 (2 bytes/px) is used instead of ARGB8888.

Usage (from repo root, needs Pillow):
    uv run --with pillow python tools/gen_background.py
"""
from PIL import Image

SRC_PATH = "images/background.png"
OUT_PATH = "ui_background.c"

# ST7796_W/H (wilibsp/bsp/display/st7796.h) minus ui_shell.c's app_bar (36px)
# and bottom bar (56px) heights.
CONTENT_W = 480
CONTENT_H = 320 - 36 - 56


def main():
    im = Image.open(SRC_PATH).convert("RGB")
    scale = min(CONTENT_W / im.width, CONTENT_H / im.height)
    w = round(im.width * scale)
    h = round(im.height * scale)
    im = im.resize((w, h), Image.LANCZOS)

    pixels = []
    for r, g, b in im.getdata():
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        pixels.append(rgb565)

    lines = [
        "// Home screen background image. GENERATED by tools/gen_background.py --",
        "// do not hand-edit; edit images/background.png and re-run that script",
        "// instead.",
        "#include \"ui_background.h\"",
        "#include \"pico/stdlib.h\"   // __in_psram, via pico/platform/sections.h",
        "",
        f'static const uint16_t __in_psram("background") bg_pixels[{w * h}] = {{',
    ]
    for i in range(0, len(pixels), 12):
        row = ", ".join(f"0x{v:04x}" for v in pixels[i:i + 12])
        lines.append(f"    {row},")
    lines.append("};")
    lines.append("")
    lines += [
        "const lv_image_dsc_t ui_background = {",
        "    .header = {",
        "        .magic = LV_IMAGE_HEADER_MAGIC,",
        "        .cf = LV_COLOR_FORMAT_RGB565,",
        f"        .w = {w},",
        f"        .h = {h},",
        "    },",
        "    .data_size = sizeof(bg_pixels),",
        "    .data = (const uint8_t *)bg_pixels,",
        "};",
    ]

    with open(OUT_PATH, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH} ({w}x{h}, {w * h * 2} bytes)")


if __name__ == "__main__":
    main()
