#!/usr/bin/env python3
"""Regenerate apps/wilicankit/ui_icons.c from tools/icon_src/*.png.

Icon source: Tabler Icons (MIT licensed), https://github.com/tabler/tabler-icons
PNG renders downloaded from the @tabler/icons-png package via jsDelivr:
    https://cdn.jsdelivr.net/npm/@tabler/icons-png@3.31.0/icons/outline/<name>.png
(same "outline" icon set as the .svg originals already in tools/icon_src/).

An earlier attempt rasterized the .svg sources directly at runtime via
LVGL's own SVG renderer (LV_USE_SVG) -- dropped because its
LV_USE_VECTOR_GRAPHIC/LV_USE_MATRIX/LV_USE_FLOAT prerequisites overflowed
this copy_to_ram build's SRAM by ~28KB. Pre-made PNGs plus a build-time
Pillow conversion (this script) sidestep needing any SVG rasterizer, at
runtime or at build time, entirely.

Conversion: each 240x240 RGBA PNG is downscaled to 24x24 with Pillow
(LANCZOS resample), and only its alpha channel is kept -- these are
monochrome outline icons, so alpha alone fully describes the shape. The
result is emitted as an LV_COLOR_FORMAT_A8 (alpha-only) lv_image_dsc_t
per icon; apps/wilicankit/ui_shell.c tints them at draw time via
lv_obj_set_style_image_recolor()/_recolor_opa().

Usage (from repo root, needs Pillow: `pip install pillow`):
    python tools/gen_icons.py
"""
from PIL import Image

ICONS = [
    # (C symbol suffix, tools/icon_src/<src>.png)
    ("monitor", "device-desktop"),
    ("transmit", "upload"),
    ("diagnostics", "stethoscope"),
    ("setup", "settings"),
    ("controls", "adjustments-horizontal"),
    ("back", "arrow-left"),
    ("load", "folder"),
    ("signals", "activity"),
    ("messages", "mail"),
    ("plus", "plus"),
    ("save", "device-floppy"),
    ("delete", "trash"),
    ("new", "file-plus"),
    ("online", "plug-connected"),
    ("offline", "plug-off"),
    ("health", "ambulance"),
    ("sine", "wave-sine"),
]
SIZE = 24
OUT_PATH = "ui_icons.c"


def alpha_bytes(src_name):
    im = Image.open(f"tools/icon_src/{src_name}.png").convert("RGBA")
    im = im.resize((SIZE, SIZE), Image.LANCZOS)
    return im.split()[-1].tobytes()  # A channel only, row-major


def main():
    lines = [
        "// Bottom-nav / sub-tab icons -- pre-rendered 24x24 alpha-only (A8)",
        "// bitmaps. GENERATED by tools/gen_icons.py -- do not hand-edit; edit",
        "// tools/icon_src/*.png and re-run that script instead.",
        "//",
        "// Source: Tabler Icons (MIT licensed), https://github.com/tabler/tabler-icons",
        "// PNGs fetched from the @tabler/icons-png package via jsDelivr",
        "// (https://cdn.jsdelivr.net/npm/@tabler/icons-png@3.31.0/icons/outline/),",
        "// the same \"outline\" set as the .svg originals in tools/icon_src/.",
        "//",
        "// A8 = alpha only (no color of its own); ui_shell.c tints these via",
        "// lv_obj_set_style_image_recolor()/_recolor_opa().",
        "#include \"ui_icons.h\"",
        "#include \"pico/stdlib.h\"   // __in_psram, via pico/platform/sections.h",
        "",
    ]

    for var, src in ICONS:
        data = alpha_bytes(src)
        lines.append(f'static const uint8_t __in_psram("icons") icon_data_{var}[{len(data)}] = {{')
        for i in range(0, len(data), 16):
            row = ", ".join(str(b) for b in data[i:i + 16])
            lines.append(f"    {row},")
        lines.append("};")
        lines.append("")

    lines += [
        "#define ICON_DSC(sym, data_sym) \\",
        "    const lv_image_dsc_t sym = { \\",
        "        .header = { \\",
        "            .magic = LV_IMAGE_HEADER_MAGIC, \\",
        "            .cf = LV_COLOR_FORMAT_A8, \\",
        f"            .w = {SIZE}, \\",
        f"            .h = {SIZE}, \\",
        "        }, \\",
        "        .data_size = sizeof(data_sym), \\",
        "        .data = data_sym, \\",
        "    }",
        "",
    ]
    for var, _ in ICONS:
        lines.append(f"ICON_DSC(ui_icon_{var}, icon_data_{var});")

    with open(OUT_PATH, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
